import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className="text-base bg-primary-pale h-screen flex">
      <Head>
        <title>Order Summary Component</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Red+Hat+Display:wght@500;700;900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className="max-w-[360px] m-auto rounded-3xl text-center pb-6 bg-neutral-pale flex flex-col">
        <img
          src="images/illustration-hero.svg"
          alt=""
          className="rounded-t-3xl"
        />
        <h1 className="text-2xl font-bold mt-6">Order Summary</h1>
        <p className="mt-6 w-5/6 m-auto text-lg text-neutral-desaturated">
          You can now listen to millions of songs, audiobooks, and podcasts on
          any device anywhere you like!
        </p>
        <section className="flex justify-between w-5/6 m-auto mt-6 align-middle bg-primary-pale bg-opacity-40 px-4 py-2 rounded-xl">
          <img src="images/icon-music.svg" alt="" />
          <div className="text-left">
            <h2 className="font-bold">Annual Plan</h2>
            <h2 className="text-neutral-desaturated">$59.99/year</h2>
          </div>
          <span className="underline text-neutral-dark flex flex-col justify-center font-bold hover:cursor-pointer hover:no-underline hover:text-primary-bright hover:text-opacity-60">
            Change
          </span>
        </section>
        <button className="mt-8 font-bold text-md text-primary-pale bg-primary-bright w-5/6 m-auto rounded-xl p-3 shadow-neutral-desaturated shadow-lg drop-shadow-2xl hover:bg-primary-bright hover:bg-opacity-60 hover:cursor-pointer">
          Proceed to Payment
        </button>
        <span className="mt-4 text-neutral-desaturated font-bold hover:text-neutral-dark hover:cursor-pointer">
          Cancel Order
        </span>
      </main>

      <footer className=""></footer>
    </div>
  );
};

export default Home;
